# Generated by Django 4.2.7 on 2024-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0004_student_kruzok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kruzok',
            options={'ordering': ['nazov'], 'verbose_name': 'Kruzok', 'verbose_name_plural': 'Kruzky'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Student', 'verbose_name_plural': 'Studenti'},
        ),
        migrations.AlterModelOptions(
            name='trieda',
            options={'ordering': ['nazov'], 'verbose_name': 'Trieda', 'verbose_name_plural': 'Triedy'},
        ),
        migrations.AlterModelOptions(
            name='ucitel',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Ucitel', 'verbose_name_plural': 'Ucitelia'},
        ),
        migrations.AddField(
            model_name='student',
            name='obec',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='psc',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ulica',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
