# Generated by Django 5.0 on 2024-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0006_ucitel_obec_ucitel_psc_ucitel_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datum_narodenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='datum_narodenia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
