# Generated by Django 5.0 on 2024-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoria',
            name='nazov',
            field=models.CharField(max_length=40),
        ),
    ]
