# Generated by Django 5.0 on 2024-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_kategoria_nazov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nazov',
            field=models.CharField(max_length=100),
        ),
    ]
